################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@host = http://localhost:{{$dotenv PORT}}

### GET /v1/cadex
GET {{host}}/v1/cadex

### GET /v1/cadex?verb=allume%20le%20feu%20de
GET {{host}}/v1/cadex?name=Le%20petit%20dodo&verb=crounche
